title:  "Arlo O'Keeffe"
description: "Stuff done by Arlo O'Keeffe"
exclude: [Gemfile, Gemfile.lock, Rakefile, gravatar-favicon.sh, arlol-github-page.sublime-project, arlol-github-page.sublime-workspace]
markdown: kramdown
